### ISSUE TITLE
Notes on installation, Debian Jessie

### ISSUE THREAD

**Issue by thestumbler** [tigersoldier/osd-lyrics#8]
[configure.ac.zip](https://github.com/tigersoldier/osd-lyrics/files/142251/configure.ac.zip)

I had to make some modifications to get this to build on my Debian 8 system.  Just wanted to post this, in case anyone else runs into the same issue.  When you first try to run autoconf in order to generate the configure file, you get a bunch of error messages.  I was able to correct them by editing configure.ac and running several configuration commands.
1. added this line to configure.ac
   `AC_CONFIG_MACRO_DIR([m4])`
   _see [Will Robert's reply #2 in this forum here](https://bbs.archlinux.org/viewtopic.php?id=161452) _
2. Installed the xorg-server-source package based on the notes in the above thread
   (not sure this is necessary or not).  I already had the other packages mentioned installed.
3. Added this option to configure.ac:
   AM_INIT_AUTOMAKE([subdir-objects])
   [see this forum thread here](https://github.com/tatsuhiro-t/aria2/issues/120)
   Actually, AM_INIT_AUTOMAKE is already in the file, so I just edited to add the new parameter:
   `AM_INIT_AUTOMAKE([-Wall -Werror subdir-objects])`

After editing the .ac file, I followed the sequence of commands listed
in the reference from #1 above.

```
$ libtoolize --force
$ aclocal
$ autoheader
$ automake --force-missing --add-missing
$ autoconf
```

Note: I still get a few of these errors:
`sh: 1: test: x: unexpected operator`
during the `aclocal` and `automake` commands, but it appears they can be safely ignored.

I then proceeded with `./configure, make, sudo make install` as usual, with no
problems.

My modified `configure.ac` file is attached.

**Comment by lenoch** [comment]
Hi,

can you please try to build https://github.com/PedroHLC/osdlyrics/ (the forked upstream)?

Version 0.5 (in development) is the default branch there. Python is much more used in 0.5 (@tigersoldier has done this long ago) so some dependencies are gone while some more are needed.

You can refer to https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=osdlyrics-git to learn about the dependencies you may need to install on Debian:

> depends=(dbus-glib desktop-file-utils gtk2 hicolor-icon-theme libnotify python2-dbus python2-chardet python2-gobject2 python2-pycurl sqlite)

**Comment by thestumbler** [comment]
Yep, that seems to help quite a bit.  
The `configure.ac` file was still missing the macro-dir directive, but running 

```
$ autoconf
$ autoreconfig -i
```

did the trick for me and created a workable configure file.

Still have those `sh: 1: test: x: unexpected operator` errors, but it is working now.
Thanks.

**Comment by lenoch** [comment]
If you could isolate the file that caused the "unexpected operator" errors (used by `aclocal`/`automake`) we could fix them.

It seems `sh` is used instead of `bash`, as http://stackoverflow.com/questions/3411048/unexpected-operator-in-shell-programming suggests.

**Comment by thestumbler** [comment]
I'll try to check that and report back. 

You mean I should actually run the install process from sh rather than bash? It's been awhile since I looked into this topic, but as I recall sh may be linked to bash on my Debian installation. I'll confirm and try to make it really point to sh. 

I'm going to make a branch to add a special purpose lyrics output, basically sending the text over the serial port. This is the latest and correct branch to build from? 

-Chris 

Sent from my android device.

-----Original Message-----

**Comment by lenoch** [comment]
I mean `bash` should be the shell `aclocal`/`automake` should call, not `sh`, as it lacks some of the syntax/expressions `bash` supports and is probably present in `configure.ac`.

Yes, https://github.com/PedroHLC/osdlyrics/ is the most complete osdlyrics repository. @PedroHLC has made a lot of effort to merge patches proposed for the original repositories and he is quick to respond to pull requests. I think it is worth adding a git remote pointing to his repository.

I am looking forward to your patches :-)
